### ISSUE TITLE
Invalid https certificate

### ISSUE THREAD

**Issue by SuperSandro2000** [pioul/Minimalist-Online-Markdown-Editor#19]
The certificate on http://markdown.pioul.fr is invalid and you are not automatically redirecting to https which is standard now days and should be standard with an editor where I could enter personal information.

**Comment by pioul** [comment]
Hi! https was not available at the time on the free web hosting I use to host this open source editor, but it now is. It's still not redirecting automatically to https, but feel free to access https://markdown.pioul.fr :)

No data is ever sent out of your browser so there's that, but you're right that https has been a standard for years now and it should be used for everything!
